server:
  port: 8080
  servlet:
    context-path: /vaccination-module-backend
  forward-headers-strategy: framework

spring:
  application:
    name: Vaccination Module for the EPR
    version: '@project.version@'
  profiles:
    active: ${SPRING_CLOUDPROFILES_ACTIVE:local}
  config:
    import: >
      file:${vaccination_config:config}/portal-config.yml,
      file:${vaccination_config:config}/husky.yml,
      file:${vaccination_config:config}/idp-config-${SPRING_CLOUDPROFILES_ACTIVE:local}.yml,
      file:${vaccination_config:config}/fhir.yml,
      file:${vaccination_config:config}/valuelists/vaccines-to-targetdiseases.yml,
      file:${vaccination_config:config}/valuelists/pdf-output.yml,
      optional:file:${vaccination_config:config}/logging.properties
  banner:
    location: banner.txt
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Logging Configuration
logging:
  file:
    name: ${LOG_PATH:/opt/adswiss/vaccination-module/log}/vacc-backend.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_PATH:/opt/adswiss/vaccination-module/log}/archived/vacc-backend-%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 50MB
      max-history: 30
  level:
    root: DEBUG

# path for actuator
management:
  security:
    enabled: false
  health:
    probes:
      enabled: true 

springdoc:
  swagger-ui:
    path: /swagger
  swagger:
    title: Vaccination Backend API
    description: Provides REST controller to connect the Backend and the Angular Frontend
    license: MIT
    licenseUrl: https://www.mit.edu/~amini/LICENSE.md
    version: 1.0

# see : https://docs.hazelcast.com/imdg/4.2/cp-subsystem/configuration
hazelcast:
  cp-subsystem:
    cp-member-count: 1 # Minimal configuration
    group-size: 1      # to ensure safe mode or consistency.

# Application relevant configuration
application:
  # local mode: only set during dev!
  localMode: ${LOCALMODE:false}
  # husky local mode: only set during dev!
  huskyLocalMode: ${HUSKYLOCALMODE:false}
  # Specifies CORS Access-Control-Allow-Origin - * allows all origins)
  frontendUrl: ${FRONTEND_URL:http://localhost:4200,http://localhost:9000}
  frontendDomain: ${FRONTEND_DOMAIN:}
  valueListPath: ${vaccination_config:config}/valuelists

vaccination:
  # Document Metadata
  formatCodes:
    - code: urn:che:epr:ch-vacd:immunization-administration:2022
      codeSystem: 2.16.756.5.30.1.127.3.10.10
      displayName: CH VACD Immunization Administration
    - code: urn:che:epr:ch-vacd:vaccination-record:2022
      codeSystem: 2.16.756.5.30.1.127.3.10.10
      displayName: CH VACD Vaccination Record
  doctor:
    authorSpeciality: 
      code: 1050
      displayName: Other
      codeSystem: 2.16.756.5.30.1.127.3.5
    healthCareFacilityTypeCode: 
      code: 43741000
      displayName: Site of Care (environment)
      codeSystem: 2.16.840.1.113883.6.96
    practiceSettingCode: 
      code: 394802001
      displayName: General medicine (qualifier value) 
      codeSystem: 2.16.840.1.113883.6.96
  patient:
    authorSpeciality:
      code: 1050
      displayName: Other
      codeSystem: 2.16.756.5.30.1.127.3.5
    healthCareFacilityTypeCode: 
      code: 66280005
      displayName: Private home-based care (environment)
      codeSystem: 2.16.840.1.113883.6.96
    practiceSettingCode:
      code: 394802001
      displayName: General medicine (qualifier value 
      codeSystem: 2.16.840.1.113883.6.96
  documentType: 41000179103
  systemIdentifier: urn:ietf:rfc:3986