epdbackend:
  # Logging of soap messages, for testing purpose only, put to false on prod machines.
  activateSoapLogging: false
  soapLoggingPath: ${vaccination_config:config}/log/
  
  sender:
    applicationOid: "1.2.3.4"
    facilityOid: 

  communities:
    # EPD Backend configuration 
    - identifier: EPDBackend
      globalAssigningAuthorityOid: "1.2.3.4.5.6.7.8.9"
      spidEprOid: "1.2.3.4.5.6.7.8.9"
      spidEprNamespace: ""
      repositories:
        # PDQ: Query the master patient ID and EPR-SPID for patients
        - identifier: PDQ
          uri: https://configure.me/pdq
          receiver:
            applicationOid: "1.2.3.4.5.6.7.8.9"
            facilityOid: "1.2.3.4.5.6.7.8.9"

        # Registry Stored Query: Get and display document metadata
        - identifier: RegistryStoredQuery
          uri: https://configure.me/RegistryStoredQuery
          receiver:
            applicationOid: "1.2.3.4.5.6.7.8.9"
            facilityOid: "1.2.3.4.5.6.7.8.9"

        # Retrieve Document Set: Get and display document contents
        - identifier: RetrieveDocumentSet
          uri: https://configure.me/RetrieveDocumentSet
          receiver:
            applicationOid: "1.2.3.4.5.6.7.8.9"
            facilityOid: "1.2.3.4.5.6.7.8.9"

        # Submit Document Set: Submit a document contents
        - identifier: SubmitDocument
          uri: https://configure.me/RetrieveDocumentSet
          receiver:
            applicationOid: "1.2.3.4.5.6.7.8.9"
            facilityOid: "1.2.3.4.5.6.7.8.9"
            
        # XUA / STS: Get X-User Assertion
        - identifier: XUA
          uri: https://configure.me/XUA
          receiver:
            applicationOid: "1.2.3.4.5.6.7.8.9"
            facilityOid: "1.2.3.4.5.6.7.8.9"
          xua:
            clientKeyStoreType: keystore.type.eg.jks
            clientKeyStore: path.to.keystore
            clientKeyStorePass: keystore.password

# Configuration of the ATNA Logging provided by the husky framework
ipf:
  atna:
    audit-enabled: true
    audit-repository-host: localhost
    audit-repository-port: 9898
    # For TCP, ATNA needs TLS which is implies that the default 
    # Keystore contains a private key which is known to the ATNA server
    # Additionally, default java truststore must contain ATNA server's public key / certificate
    audit-repository-transport: TLS