epdbackend:
  sender:
    applicationOid: "1.2.3.4"
    facilityOid: 

  communities:
    # empty community without configuration
    - identifier: DUMMY
    # EPD Backend configuration 
    - identifier: EPDBackend
      globalAssigningAuthorityOid: "1.2.3.4.5.6.7.8.9"
      spidEprOid: "1.2.3.4.5.6.7.8.9"
      repositories:
        # PDQ: Query the master patient ID and EPR-SPID for patients
        - identifier: PDQ
          uri: https://configure.me/pdq
          receiver:
            applicationOid: "1.2.3.4.5.6.7.8.9"
            facilityOid: "1.2.3.4.5.6.7.8.9"

        # Registry Stored Query: Get and display document metadata
        - identifier: RegistryStoredQuery
          uri: https://configure.me/RegistryStoredQuery
          receiver:
            applicationOid: "1.2.3.4.5.6.7.8.9"
            facilityOid: "1.2.3.4.5.6.7.8.9"

        # Retrieve Document Set: Get and display document contents
        - identifier: RetrieveDocumentSet
          uri: https://configure.me/RetrieveDocumentSet
          receiver:
            applicationOid: "1.2.3.4.5.6.7.8.9"
            facilityOid: "1.2.3.4.5.6.7.8.9"

        # Submit Document Set: Submit a document contents
        - identifier: SubmitDocument
          uri: https://configure.me/RetrieveDocumentSet
          receiver:
            applicationOid: "1.2.3.4.5.6.7.8.9"
            facilityOid: "1.2.3.4.5.6.7.8.9"
            
        # ATNA: EPD Logging
        - identifier: ATNA
          uri: https://configure.me:1234
          receiver:
            applicationOid: "1.2.3.4.5.6.7.8.9"
            facilityOid: "1.2.3.4.5.6.7.8.9"

        # XUA / STS: Get X-User Assertion
        - identifier: XUA
          uri: https://configure.me/XUA
          receiver:
            applicationOid: "1.2.3.4.5.6.7.8.9"
            facilityOid: "1.2.3.4.5.6.7.8.9"
            
    # eHealth Suisse reference environment
    - identifier: EPDPLAYGROUND
      globalAssigningAuthorityOid: "1.1.1.99.1" 
      spidEprOid: "2.16.756.5.30.1.127.3.10.3"
      repositories:
        - identifier: PDQ
          uri: https://epdplayground.i4mi.bfh.ch:7443/PIXPDQ/services/PIXPDQV3ManagerService
          receiver:
            applicationOid: "1.1.1.99.1"

        # Registry Stored Query: Get and display document metadata
        - identifier: RegistryStoredQuery
          uri: https://epdplayground.i4mi.bfh.ch:7443/Registry/services/RegistryService
          receiver:
            applicationOid:  "2.16.840.1.113883.3.72.6.5.100.1399"

        # Retrieve Document Set: Get and display document contents
        - identifier: RetrieveDocumentSet
          uri: https://epdplayground.i4mi.bfh.ch:6443/Repository/services/RepositoryService
          homeCommunityOid: "urn:oid:1.1.1"
          receiver:
            applicationOid: "2.16.840.1.113883.3.72.6.5.100.1399"

        # Submit Document Set: Submit a document contents
        - identifier: SubmitDocument
          uri: https://epdplayground.i4mi.bfh.ch:6443/Repository/services/RepositoryService
          receiver:
            applicationOid: Clinical Information System

        # ATNA: EPD Logging
        - identifier: ATNA
          uri: https://epdplayground.i4mi.bfh.ch:5234
          receiver:
            applicationOid: "1.3.6.1.4.1.21367.2017.2.5.97"
            facilityOid: "1.3.6.1.4.1.21367.2017.2.7.127"

        # XUA / STS: Get X-User Assertion
        - identifier: XUA
          uri: https://ehealthsuisse.ihe-europe.net:10443/STS?wsdl
          receiver:
            applicationOid: "1.3.6.1.4.1.21367.2017.2.5.97"
            facilityOid: "1.3.6.1.4.1.21367.2017.2.7.127"

    # eHS Reference environment
    - identifier: GAZELLE
      globalAssigningAuthorityOid: "1.3.6.1.4.1.12559.11.20.1"
      spidEprOid: "2.16.756.5.30.1.127.3.10.3"
      repositories:
        # PDQ: Search for patient data using demographic data as search criteria
        - identifier: PDQ
          uri: https://ehealthsuisse.ihe-europe.net/PAMSimulator-ejb/PDQSupplier_Service/PDQSupplier_PortType
          receiver:
            applicationOid: "2.16.840.1.113883.3.72.6.5.100.1399"
            facilityOid:

        # Registry Stored Query: Get and display document metadata
        - identifier: RegistryStoredQuery
          uri: http://ehealthsuisse.ihe-europe.net:8280/xdstools7/sim/epr-testing__for_init_gw_testing/rep/xcq
          receiver:
            applicationOid: "2.16.840.1.113883.3.72.6.5.100.1399"
            facilityOid:

        # Retrieve Document Set: Get and display document contents
        - identifier: RetrieveDocumentSet
          uri: http://ehealthsuisse.ihe-europe.net:8280/xdstools7/sim/epr-testing__for_init_gw_testing/rep/ret
          receiver:
            applicationOid: "2.16.840.1.113883.3.72.6.5.100.1399"
            facilityOid:
  
        # Submit Document Set: Submit a document contents
        - identifier: SubmitDocument
          uri: http://ehealthsuisse.ihe-europe.net:8280/xdstools7/sim/epr-testing__for_init_gw_testing/rep/prb
          receiver:
            applicationOid: "2.16.840.1.113883.3.72.6.5.100.1399"
            facilityOid:

        # ATNA: EPD Logging
        - identifier: ATNA
          uri: https://epd-test.ith-icoserve.com:7443/ARR/fhir
          receiver:
            applicationOid: "1.3.6.1.4.1.21367.2017.2.5.97"
            facilityOid: "1.3.6.1.4.1.21367.2017.2.7.127"

        # XUA / STS: Get X-User Assertion
        - identifier: XUA
          uri: https://ehealthsuisse.ihe-europe.net:10443/STS?wsdl
          receiver:
            applicationOid: "1.3.6.1.4.1.21367.2017.2.5.97"
            facilityOid: "1.3.6.1.4.1.21367.2017.2.7.127"