# Identity Provider
idp:
  # SP Entity ID that is known to the IdP
  knownEntityId: https://my.backend.url/

  # Provide per Provider
  # HTTP-Post Binding URL
  # SAML2.0-SOAP Binding URL 
  supportedProvider:
  - identifier: GAZELLE
    authnrequestURL: https://ehealthsuisse.ihe-europe.net:4443/idp/profile/SAML2/POST/SSO
    artifactResolutionServiceURL: https://ehealthsuisse.ihe-europe.net:4443/idp/profile/SAML2/SOAP/ArtifactResolution 
  # Dummy Provider for testing purpose
  - identifier: DUMMY
    
# Service Provider - this application
sp:
  assertionConsumerServiceUrl: https://my.backend.url/saml/sso
    
  # keystore containing our private key
  keystore:
   keystore-path: path.to.keystore
   keystore-password: keystore.password
   sp-alias: key.alias.used.for.idp