# Identity Provider
idp:
  # SP Entity ID that is known to the IdP
  knownEntityId: https://my.backend.url/

  # SAML Message validation
  # Allowed derivation (in ms) between sending an SAML request and receiving the response, default 2000
  samlMessageLifetime: 2000
  # Allowed clockskew (there should be none if both run with the same NTP), default 1000
  samlMessageClockSkew: 1000
  
  # Provide per Provider 
  supportedProvider:
  - identifier: GAZELLE
    authnrequestURL: https://ehealthsuisse.ihe-europe.net:4443/idp/profile/SAML2/POST/SSO
    artifactResolutionServiceURL: https://ehealthsuisse.ihe-europe.net:4443/idp/profile/SAML2/SOAP/ArtifactResolution
    securityTokenServiceURL: https://is.not.set.for.gazelle
    entityId: OverwriteDefaultEntityIDIfNecessary
    logoutURL: https://logout.url.set.in.logout.request.destination
  - identifier: DUMMY
  
# Service Provider - this application
sp:
  assertionConsumerServiceUrl: https://my.backend.url/saml/sso
  forwardArtifactToClientUrl: https://my.frontend.url/saml-acs

  # keystore containing our private key
  keystore:
   keystore-type: PKCS12
   keystore-path: path.to.keystore
   keystore-password: keystore.password
   sp-alias: key.alias.used.for.idp