# Identity Provider
idp:
  # SP Entity ID that is known to the IdP
  knownEntityId: https://my.backend.url/

  # SAML Message validation
  # Allowed derivation (in ms) between sending an SAML request and receiving the response, default 2000
  samlMessageLifetime: 2000
  # Allowed clockskew (there should be none if both run with the same NTP), default 1000
  samlMessageClockSkew: 1000
  
  # Provide per Provider 
  supportedProvider:
  - identifier: GAZELLE
    authnrequestURL: https://ehealthsuisse.ihe-europe.net:4443/idp/profile/SAML2/POST/SSO
    artifactResolutionServiceURL: https://ehealthsuisse.ihe-europe.net:4443/idp/profile/SAML2/SOAP/ArtifactResolution
    securityTokenServiceURL: https://is.not.set.for.gazelle
    entityId: OverwriteDefaultEntityIDIfNecessary
    logoutURL: https://logout.url.set.in.logout.request.destination
    samlKeystore: # IDP specific setting overriding the sp.keystore setting 
      keystoreType: PKCS12
      keystorePath: path.to.keystore.p12
      keystorePassword: password
      spAlias: spkeyAlias
    tlsKeystore: # IDP specific setting overriding the sp.tlsKeystore setting
      keystoreType: JKS
      keystorePath: path.to.keystore.jks
      keystorePassword: password
  - identifier: DUMMY
  
# Service Provider - this application
sp:
  assertionConsumerServiceUrl: https://my.backend.url/saml/sso
  forwardArtifactToClientUrl: https://my.frontend.url/saml-acs
  otherNodeLogoutURL: https://otherNode.backend.url/saml/logout

  # keystore containing the private key used for MTLS with the EPD backend
  keystore:
   keystore-type: PKCS12
   keystore-path: path.to.keystore
   keystore-password: keystore.password
   sp-alias: key.alias.used.for.idp
  # Keystore containing the private key used for MTLS with the IDPs
  tlsKeystore:
    keystore-type: JKS
    keystore-path: path.to.keystore.jks
    keystore-password: password 