pdf-output:
  legalCommentVisible: false
  basicVaccination:
    keepEmpty: true
    codes:
      - 397430003  #Diphtherie
      - 76902006   #Starrkrampf, Tetanus
      - 27836007   #Keuchhusten, Pertussis
      - 398102009  #Akute Poliomyelitis
      - 709410003  #Infektion mit Haemophilus influenzae Typ B
      - 66071002   #Virale Hepatitis, Typ B
      - 16814004   #Pneumokokken-Erkrankung
      - 14189004   #Masern
      - 36989005   #Mumps
      - 36653000   #Röteln
      - 240532009  #HPV-Erkrankung (Humanes Papillomavirus)
  otherVaccination:
    keepEmpty: false
    codes:
      - 40468003 # Viral hepatitis, type A (disorder)
      - 23511006 # Meningokokken-Erkrankung
      - 712986001 # Frühsommer-Meningoenzephalitis (FSME)
      - 38907003 # Windpocken/varicelle
      - 56717001 # Tuberkulose
      - 4740000  # Herpes zoster
      - 840539006 # COVID-19
      - 14168008 # Tollwut
      - 16541001 # Gelbfieber
      - 63650001 # Cholera
      - 18624000 # Rotavirus disease
      - 4834000 # Typhoid fever
      - 52947006 # Japanese encephalitis
      - 719865001 # Influenza caused by pandemic influenza virus
      - 719590007 # Influenza caused by seasonal influenza virus
      - 67924001 # Smallpox
      - 359814004 # Monkeypox
      - 37109004 # EVD-Ebola virus disease